'use client';
import { useState } from 'react';
import { Copy, Download, Check, Sparkles, Palette, RefreshCw, Code2, Layers, Zap, Image as ImageIcon } from 'lucide-react';
import Breadcrumbs from '@/components/seo/Breadcrumbs';

/* ─── Background presets ─────────────────────────────────────────────────── */
const BG_PRESETS = {
  mesh: 'radial-gradient(at 40% 20%, hsla(28,100%,74%,1) 0px, transparent 50%), radial-gradient(at 80% 0%, hsla(189,100%,56%,1) 0px, transparent 50%), radial-gradient(at 0% 50%, hsla(355,100%,93%,1) 0px, transparent 50%), radial-gradient(at 80% 50%, hsla(340,100%,76%,1) 0px, transparent 50%), radial-gradient(at 0% 100%, hsla(22,100%,77%,1) 0px, transparent 50%), radial-gradient(at 80% 100%, hsla(242,100%,70%,1) 0px, transparent 50%), radial-gradient(at 0% 0%, hsla(343,100%,76%,1) 0px, transparent 50%)',
  aurora: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
  sunset: 'linear-gradient(135deg, #fa709a 0%, #fee140 50%, #30cfd0 100%)',
  ocean: 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #4facfe 75%, #00f2fe 100%)',
  midnight: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
  neon: 'linear-gradient(135deg, #ff0844 0%, #ffb199 50%, #ff0844 100%)',
  forest: 'linear-gradient(135deg, #134e5e 0%, #71b280 50%, #134e5e 100%)',
  cosmic: 'linear-gradient(135deg, #232526 0%, #414345 50%, #232526 100%)',
  vibrant: 'linear-gradient(135deg, #ee9ca7 0%, #ffdde1 25%, #a8edea 50%, #fed6e3 75%, #ee9ca7 100%)',
};

/* ─── Helper ─────────────────────────────────────────────────────────────── */
function hexToRgb(hex) {
  const r = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return r ? { r: parseInt(r[1], 16), g: parseInt(r[2], 16), b: parseInt(r[3], 16) } : { r: 255, g: 255, b: 255 };
}

/* ─── Slider component ───────────────────────────────────────────────────── */
function Slider({ label, value, setValue, min, max, unit, accent = '#8b5cf6' }) {
  const pct = ((value - min) / (max - min)) * 100;
  return (
    <div>
      <div className="flex justify-between items-center mb-2">
        <label className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wide">{label}</label>
        <span className="text-xs font-mono font-bold text-slate-900 dark:text-white bg-slate-100 dark:bg-slate-700 px-2.5 py-1 rounded-lg">{value}{unit}</span>
      </div>
      <div className="relative h-5 flex items-center">
        <div className="absolute w-full h-2 bg-slate-200 dark:bg-slate-700 rounded-full">
          <div className="h-full rounded-full bg-violet-500 transition-all" style={{ width: `${pct}%` }} />
        </div>
        <input type="range" min={min} max={max} value={value}
          onChange={e => setValue(Number(e.target.value))}
          className="absolute w-full h-2 opacity-0 cursor-pointer z-10" />
        <div className="absolute w-5 h-5 bg-white border-2 border-violet-500 rounded-full shadow-md pointer-events-none transition-all"
          style={{ left: `calc(${pct}% - 10px)` }} />
      </div>
    </div>
  );
}

export default function GlassmorphismGenerator() {
  const [blur, setBlur] = useState(16);
  const [opacity, setOpacity] = useState(15);
  const [saturation, setSaturation] = useState(180);
  const [borderOpacity, setBorderOpacity] = useState(20);
  const [borderWidth, setBorderWidth] = useState(1);
  const [borderRadius, setBorderRadius] = useState(24);
  const [shadowX, setShadowX] = useState(0);
  const [shadowY, setShadowY] = useState(24);
  const [shadowBlur, setShadowBlur] = useState(48);
  const [shadowOpacity, setShadowOpacity] = useState(12);
  const [bgColor, setBgColor] = useState('#ffffff');
  const [bgType, setBgType] = useState('mesh');
  const [customBg, setCustomBg] = useState('#667eea');
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState('css');
  const [cardPadding, setCardPadding] = useState(32);
  const [contentColor, setContentColor] = useState('white'); // 'white' | 'dark'

  const currentBg = bgType === 'custom' ? customBg : BG_PRESETS[bgType];

  const rgb = hexToRgb(bgColor);

  const glassStyle = {
    background: `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${opacity / 100})`,
    backdropFilter: `blur(${blur}px) saturate(${saturation}%)`,
    WebkitBackdropFilter: `blur(${blur}px) saturate(${saturation}%)`,
    borderRadius: `${borderRadius}px`,
    border: `${borderWidth}px solid rgba(255, 255, 255, ${borderOpacity / 100})`,
    boxShadow: `${shadowX}px ${shadowY}px ${shadowBlur}px rgba(0, 0, 0, ${shadowOpacity / 100})`,
    padding: `${cardPadding}px`,
  };

  const textMain = contentColor === 'white' ? '#ffffff' : '#1e293b';
  const textSub = contentColor === 'white' ? 'rgba(255,255,255,0.8)' : '#475569';

  /* ── Code generators ── */
  const generateCSS = () =>
    `/* Glassmorphism Card — generated by OmniWebKit */
.glass-card {
  background: rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${opacity / 100});
  backdrop-filter: blur(${blur}px) saturate(${saturation}%);
  -webkit-backdrop-filter: blur(${blur}px) saturate(${saturation}%);
  border-radius: ${borderRadius}px;
  border: ${borderWidth}px solid rgba(255, 255, 255, ${borderOpacity / 100});
  box-shadow: ${shadowX}px ${shadowY}px ${shadowBlur}px rgba(0, 0, 0, ${shadowOpacity / 100});
  padding: ${cardPadding}px;
}`;

  const generateSCSS = () =>
    `// Glassmorphism Card — generated by OmniWebKit
.glass-card {
  $glass-bg:     rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${opacity / 100});
  $glass-border: rgba(255, 255, 255, ${borderOpacity / 100});
  $glass-shadow: rgba(0, 0, 0, ${shadowOpacity / 100});

  background:              $glass-bg;
  backdrop-filter:         blur(${blur}px) saturate(${saturation}%);
  -webkit-backdrop-filter: blur(${blur}px) saturate(${saturation}%);
  border-radius:           ${borderRadius}px;
  border:                  ${borderWidth}px solid $glass-border;
  box-shadow:              ${shadowX}px ${shadowY}px ${shadowBlur}px $glass-shadow;
  padding:                 ${cardPadding}px;
}`;

  const generateTailwind = () => {
    const blurCls = blur >= 32 ? '3xl' : blur >= 24 ? '2xl' : blur >= 16 ? 'xl' : blur >= 12 ? 'lg' : blur >= 8 ? 'md' : 'sm';
    const rndCls = borderRadius >= 40 ? '3xl' : borderRadius >= 32 ? '2xl' : borderRadius >= 24 ? '2xl' : borderRadius >= 16 ? 'xl' : 'lg';
    const shadCls = shadowBlur >= 56 ? '2xl' : shadowBlur >= 32 ? 'xl' : 'lg';
    const opTenth = Math.round(opacity / 10);
    const borTenth = Math.round(borderOpacity / 10);
    return `<div class="
  backdrop-blur-${blurCls}
  backdrop-saturate-[${saturation}%]
  bg-white/[0.${opTenth}]
  rounded-${rndCls}
  border border-white/[0.${borTenth}]
  shadow-${shadCls}
  p-8
">
  <!-- Your content here -->
</div>`;
  };

  const generateReact = () =>
    `const GlassCard = ({ children }) => {
  const style = {
    background:              'rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${opacity / 100})',
    backdropFilter:          'blur(${blur}px) saturate(${saturation}%)',
    WebkitBackdropFilter:    'blur(${blur}px) saturate(${saturation}%)',
    borderRadius:            '${borderRadius}px',
    border:                  '${borderWidth}px solid rgba(255, 255, 255, ${borderOpacity / 100})',
    boxShadow:               '${shadowX}px ${shadowY}px ${shadowBlur}px rgba(0, 0, 0, ${shadowOpacity / 100})',
    padding:                 '${cardPadding}px',
  };
  return <div style={style}>{children}</div>;
};`;

  const getCode = () => {
    if (activeTab === 'scss') return generateSCSS();
    if (activeTab === 'tailwind') return generateTailwind();
    if (activeTab === 'react') return generateReact();
    return generateCSS();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generateCSS()], { type: 'text/css' });
    Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: 'glassmorphism.css' }).click();
  };

  const reset = () => {
    setBlur(16); setOpacity(15); setSaturation(180); setBorderOpacity(20);
    setBorderWidth(1); setBorderRadius(24); setShadowX(0); setShadowY(24);
    setShadowBlur(48); setShadowOpacity(12); setBgColor('#ffffff'); setCardPadding(32);
  };

  const PRESETS = [
    { name: 'Modern', blur: 16, opacity: 15, saturation: 180, borderOpacity: 20, borderRadius: 24, shadowY: 24, shadowBlur: 48, cardPadding: 32 },
    { name: 'Minimal', blur: 8, opacity: 10, saturation: 100, borderOpacity: 10, borderRadius: 16, shadowY: 8, shadowBlur: 24, cardPadding: 20 },
    { name: 'Bold', blur: 24, opacity: 25, saturation: 200, borderOpacity: 30, borderRadius: 32, shadowY: 32, shadowBlur: 64, cardPadding: 40 },
    { name: 'Subtle', blur: 12, opacity: 8, saturation: 120, borderOpacity: 15, borderRadius: 20, shadowY: 16, shadowBlur: 32, cardPadding: 28 },
    { name: 'Vivid', blur: 20, opacity: 18, saturation: 250, borderOpacity: 25, borderRadius: 28, shadowY: 28, shadowBlur: 56, cardPadding: 36 },
    { name: 'Elegant', blur: 14, opacity: 12, saturation: 150, borderOpacity: 18, borderRadius: 22, shadowY: 20, shadowBlur: 40, cardPadding: 30 },
  ];

  const applyPreset = (p) => {
    setBlur(p.blur); setOpacity(p.opacity); setSaturation(p.saturation);
    setBorderOpacity(p.borderOpacity); setBorderRadius(p.borderRadius);
    setShadowY(p.shadowY); setShadowBlur(p.shadowBlur); setCardPadding(p.cardPadding);
  };

  return (
    <div className="min-h-screen bg-slate-100 dark:bg-slate-900 p-4 sm:p-6 lg:p-8">
      <div className="max-w-7xl mx-auto">
        <Breadcrumbs items={[{ name: 'Glassmorphism Generator', href: '/tools/glassmorphism-generator' }]} />

        {/* Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center w-14 h-14 bg-gradient-to-br from-violet-500 to-pink-500 rounded-2xl mb-4 shadow-lg shadow-violet-500/20">
            <Sparkles className="w-7 h-7 text-white" />
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold text-slate-900 dark:text-white mb-2">Glassmorphism Generator</h1>
          <p className="text-slate-600 dark:text-slate-400 text-lg">Design frosted-glass UI effects and export CSS, SCSS, Tailwind, or React code instantly</p>
        </div>

        {/* Background picker row */}
        <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 mb-6 shadow-sm">
          <h2 className="text-sm font-bold text-slate-900 dark:text-white mb-4 flex items-center gap-2">
            <Palette className="w-4 h-4 text-violet-500" />Background Scene
          </h2>
          <div className="grid grid-cols-3 sm:grid-cols-5 lg:grid-cols-10 gap-2">
            {Object.entries(BG_PRESETS).map(([key, val]) => (
              <button key={key} onClick={() => setBgType(key)}
                className={`relative h-14 rounded-xl overflow-hidden transition-all border-2 ${bgType === key ? 'border-violet-500 scale-105 shadow-lg' : 'border-transparent hover:border-violet-300 hover:scale-103'}`}
                style={{ background: val }} title={key}>
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                <span className="absolute bottom-1 left-0 right-0 text-center text-white text-[10px] font-bold truncate px-1">
                  {key.charAt(0).toUpperCase() + key.slice(1)}
                </span>
              </button>
            ))}
            <button onClick={() => setBgType('custom')}
              className={`relative h-14 rounded-xl overflow-hidden transition-all border-2 ${bgType === 'custom' ? 'border-violet-500 scale-105 shadow-lg' : 'border-transparent hover:border-violet-300'}`}
              style={{ background: customBg }} title="Custom">
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
              <span className="absolute bottom-1 left-0 right-0 text-center text-white text-[10px] font-bold">Custom</span>
            </button>
          </div>
          {bgType === 'custom' && (
            <div className="mt-4 flex items-center gap-3">
              <input type="color" value={customBg} onChange={e => setCustomBg(e.target.value)}
                className="w-12 h-12 rounded-xl cursor-pointer border-2 border-slate-200 dark:border-slate-600 flex-shrink-0" />
              <input type="text" value={customBg} onChange={e => setCustomBg(e.target.value)} placeholder="#667eea"
                className="flex-1 px-3 py-2 border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-white rounded-xl text-sm font-mono focus:outline-none focus:border-violet-500 transition" />
            </div>
          )}
        </div>

        <div className="grid lg:grid-cols-5 gap-6">
          {/* Controls */}
          <div className="lg:col-span-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-5 shadow-sm">
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <Layers className="w-4 h-4 text-violet-500" />Controls
              </h2>
              <div className="flex items-center gap-2">
                {/* Content color toggle */}
                <button onClick={() => setContentColor(v => v === 'white' ? 'dark' : 'white')}
                  className="text-xs px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 text-slate-700 dark:text-slate-300 hover:border-violet-400 transition font-bold"
                  title="Toggle preview content colour">
                  {contentColor === 'white' ? '☀️ Light text' : '🌙 Dark text'}
                </button>
                <button onClick={reset} title="Reset to defaults"
                  className="p-2 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 rounded-xl transition text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white">
                  <RefreshCw className="w-4 h-4" />
                </button>
              </div>
            </div>

            <div className="space-y-4 max-h-[520px] overflow-y-auto pr-1">
              {/* Glass color */}
              <div className="p-3.5 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700 rounded-xl">
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wide mb-2">Glass Tint Colour</label>
                <div className="flex gap-3">
                  <input type="color" value={bgColor} onChange={e => setBgColor(e.target.value)}
                    className="w-12 h-12 rounded-xl cursor-pointer border-2 border-slate-200 dark:border-slate-600 flex-shrink-0" />
                  <input type="text" value={bgColor} onChange={e => setBgColor(e.target.value)}
                    className="flex-1 px-3 py-2 border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white rounded-xl text-sm font-mono focus:outline-none focus:border-violet-500 transition" />
                </div>
              </div>

              {[
                { label: 'Blur', value: blur, set: setBlur, min: 0, max: 40, unit: 'px' },
                { label: 'Opacity', value: opacity, set: setOpacity, min: 0, max: 100, unit: '%' },
                { label: 'Saturation', value: saturation, set: setSaturation, min: 100, max: 300, unit: '%' },
                { label: 'Border Opacity', value: borderOpacity, set: setBorderOpacity, min: 0, max: 100, unit: '%' },
                { label: 'Border Width', value: borderWidth, set: setBorderWidth, min: 0, max: 8, unit: 'px' },
                { label: 'Border Radius', value: borderRadius, set: setBorderRadius, min: 0, max: 60, unit: 'px' },
                { label: 'Padding', value: cardPadding, set: setCardPadding, min: 8, max: 72, unit: 'px' },
                { label: 'Shadow X', value: shadowX, set: setShadowX, min: -50, max: 50, unit: 'px' },
                { label: 'Shadow Y', value: shadowY, set: setShadowY, min: -50, max: 50, unit: 'px' },
                { label: 'Shadow Blur', value: shadowBlur, set: setShadowBlur, min: 0, max: 100, unit: 'px' },
                { label: 'Shadow Opacity', value: shadowOpacity, set: setShadowOpacity, min: 0, max: 100, unit: '%' },
              ].map(c => (
                <Slider key={c.label} label={c.label} value={c.value} setValue={c.set} min={c.min} max={c.max} unit={c.unit} />
              ))}
            </div>

            {/* Presets */}
            <div className="mt-5 pt-4 border-t border-slate-200 dark:border-slate-700">
              <h3 className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wide mb-3 flex items-center gap-1.5">
                <Zap className="w-3.5 h-3.5 text-amber-500" />Quick Presets
              </h3>
              <div className="grid grid-cols-3 gap-2">
                {PRESETS.map(p => (
                  <button key={p.name} onClick={() => applyPreset(p)}
                    className="px-2 py-2.5 bg-slate-50 dark:bg-slate-900/40 hover:bg-violet-50 dark:hover:bg-violet-900/20 border border-slate-200 dark:border-slate-700 hover:border-violet-400 dark:hover:border-violet-600 text-slate-700 dark:text-slate-300 hover:text-violet-700 dark:hover:text-violet-400 rounded-xl font-bold text-xs transition-all">
                    {p.name}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Preview + Code */}
          <div className="lg:col-span-3 space-y-5">
            {/* Live preview */}
            <div className="overflow-hidden rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700" style={{ background: currentBg }}>
              <div className="p-4 flex items-center justify-between" style={{ background: 'rgba(0,0,0,0.2)' }}>
                <h2 className="text-sm font-bold text-white flex items-center gap-2">
                  <Sparkles className="w-4 h-4" />Live Preview
                </h2>
                <div className="flex gap-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-400" />
                  <div className="w-3 h-3 rounded-full bg-amber-400" />
                  <div className="w-3 h-3 rounded-full bg-emerald-400" />
                </div>
              </div>
              <div className="p-8 min-h-64 flex items-center justify-center">
                <div style={glassStyle} className="w-full max-w-sm transition-all duration-300">
                  <div className="flex items-center gap-3 mb-5">
                    <div className="w-11 h-11 rounded-full flex-shrink-0" style={{ background: 'rgba(255,255,255,0.3)', border: '1px solid rgba(255,255,255,0.5)' }} />
                    <div>
                      <div className="h-3.5 w-28 rounded mb-1.5" style={{ background: 'rgba(255,255,255,0.4)' }} />
                      <div className="h-2.5 w-20 rounded" style={{ background: 'rgba(255,255,255,0.25)' }} />
                    </div>
                  </div>
                  <h3 className="text-xl font-bold mb-2 transition-colors" style={{ color: textMain }}>Glassmorphism Card</h3>
                  <p className="text-sm leading-relaxed mb-5 transition-colors" style={{ color: textSub }}>
                    Experience the frosted glass effect. Adjust blur, opacity, saturation, and more to create your perfect glass card.
                  </p>
                  <div className="flex gap-2">
                    <button className="px-4 py-2 rounded-xl text-sm font-bold transition-all"
                      style={{ background: 'rgba(255,255,255,0.25)', border: '1px solid rgba(255,255,255,0.4)', color: textMain }}>
                      Primary
                    </button>
                    <button className="px-4 py-2 rounded-xl text-sm font-bold transition-all"
                      style={{ background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', color: textSub }}>
                      Secondary
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Code output */}
            <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl shadow-sm overflow-hidden">
              <div className="flex items-center justify-between px-5 py-4 border-b border-slate-200 dark:border-slate-700">
                <h2 className="text-sm font-bold text-slate-900 dark:text-white flex items-center gap-2">
                  <Code2 className="w-4 h-4 text-violet-500" />Generated Code
                </h2>
                <div className="flex gap-2">
                  <button onClick={handleCopy}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-700 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white rounded-xl font-bold text-xs transition">
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                  <button onClick={handleDownload}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-700 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white rounded-xl font-bold text-xs transition">
                    <Download className="w-3.5 h-3.5" />CSS
                  </button>
                </div>
              </div>

              {/* Code tabs */}
              <div className="flex border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40">
                {['css', 'scss', 'tailwind', 'react'].map(tab => (
                  <button key={tab} onClick={() => setActiveTab(tab)}
                    className={`flex-1 py-2.5 text-xs font-bold uppercase tracking-wide transition border-b-2 ${activeTab === tab
                        ? 'border-violet-500 text-violet-600 dark:text-violet-400 bg-white dark:bg-slate-800'
                        : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800/50'
                      }`}>
                    {tab}
                  </button>
                ))}
              </div>

              <div className="bg-slate-900 p-5 overflow-x-auto">
                <pre className="text-sm text-emerald-400 font-mono leading-relaxed whitespace-pre-wrap"><code>{getCode()}</code></pre>
              </div>
            </div>
          </div>
        </div>

        {/* CSS property reference */}
        <div className="mt-8 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-6 shadow-sm">
          <h3 className="text-base font-bold text-slate-900 dark:text-white mb-4">CSS Property Quick Reference</h3>
          <div className="grid sm:grid-cols-3 gap-3">
            {[
              { prop: 'backdrop-filter: blur()', tip: 'The core glassmorphism property. 8–24px is the sweet spot for most designs.' },
              { prop: 'backdrop-filter: saturate()', tip: 'Increases colour vibrancy visible through the glass. 150–200% gives a vivid look.' },
              { prop: 'background: rgba()', tip: 'Controls the glass tint colour and opacity. 10–25% opacity usually looks best.' },
            ].map(({ prop, tip }) => (
              <div key={prop} className="p-4 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700 rounded-xl">
                <code className="text-xs font-mono font-bold text-violet-600 dark:text-violet-400 block mb-1.5">{prop}</code>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">{tip}</p>
              </div>
            ))}
          </div>
        </div>

        {/* SEO Content */}
        <div className="mt-8 space-y-5">
          <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-8 shadow-sm">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Free Glassmorphism CSS Generator — Create Frosted Glass UI Effects Online</h2>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
              Glassmorphism is one of the most popular UI design trends of the past few years. It creates a frosted glass appearance using CSS backdrop filters, translucent backgrounds, and subtle borders. The result is a layered, depth-rich interface that feels modern, elegant, and visually striking — especially when placed over colourful gradients or vibrant photography.
            </p>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
              The OmniWebKit Glassmorphism Generator lets you design and preview frosted glass cards in real time, then export the code in four formats: plain CSS, SCSS with variables, Tailwind CSS utility classes, and React inline styles. Every control — blur intensity, glass opacity, saturation boost, border width, border opacity, border radius, card padding, shadow position, shadow blur, and shadow opacity — updates the live preview instantly.
            </p>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
              Choose from nine background presets (mesh gradient, aurora, sunset, ocean, midnight, neon, forest, cosmic, vibrant) or enter your own custom colour. Apply one of six named presets (Modern, Minimal, Bold, Subtle, Vivid, Elegant) for a fast starting point, then fine-tune to your exact taste.
            </p>
          </div>

          <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-8 shadow-sm">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-5">What Makes Glassmorphism Work — The CSS Behind the Effect</h2>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-5">
              The glassmorphism effect is built from four CSS properties working together. Understanding what each property does helps you create better-looking glass cards and troubleshoot issues when the effect doesn't look right.
            </p>
            <div className="space-y-4">
              {[
                { prop: 'backdrop-filter: blur()', body: 'This is the single most important property for the glassmorphism effect. It blurs everything behind the element, creating the frosted glass look. The blur value is measured in pixels. Values between 8px and 24px work best — too low and the glass looks transparent rather than frosted; too high and nothing behind the card is recognisable. Note: without a vibrant background behind the card, this property has very little visible effect.' },
                { prop: 'backdrop-filter: saturate()', body: 'Applied alongside blur, saturate() boosts the colour vibrancy of everything visible through the glass. This gives the frosted glass a vivid, glowing quality that plain blurring doesn\'t achieve on its own. Values between 150% and 200% are typical. Setting it to 100% means no change; values above 200% can make the glass look very intense.' },
                { prop: 'background: rgba()', body: 'This controls the glass panel\'s tint colour and opacity. Using rgba() allows you to set how visible (opaque) the glass is. A white glass with 10–20% opacity is the classic glassmorphism look. You can use any colour — blue glass, pink glass, or even a very dark tint for a smoked glass effect — by changing the RGB values. Keep opacity low; high values make the card look like a solid-colour box rather than glass.' },
                { prop: 'border: rgba(255, 255, 255, 0.x)', body: 'A thin, semi-transparent white border catches light and defines the edge of the glass card, making it feel solid rather than floating. A 1px border at 20–30% opacity is the standard. Increasing the width to 2px or the opacity to 50% creates a more defined, modern look. A border with 0% opacity removes the edge highlight entirely.' },
                { prop: 'box-shadow', body: 'The shadow grounds the glass card and creates the sense of depth and elevation. The glassmorphism convention is to use a soft, spread-out shadow (large blur value, low opacity) rather than a crisp, dark shadow. A shadow with 0 X offset, +24px Y offset, and 48px blur at 12% opacity creates a natural floating look. The Y offset controls the perceived height of the card above the background.' },
              ].map(({ prop, body }) => (
                <div key={prop} className="flex gap-4 p-4 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700 rounded-xl">
                  <code className="text-violet-600 dark:text-violet-400 font-mono text-xs font-bold min-w-[180px] flex-shrink-0 pt-0.5">{prop}</code>
                  <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">{body}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-8 shadow-sm">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Browser Support and the -webkit- Prefix</h2>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
              The <code className="text-violet-600 dark:text-violet-400 font-mono text-sm">backdrop-filter</code> property has broad support in modern browsers, but requires the <code className="text-violet-600 dark:text-violet-400 font-mono text-sm">-webkit-backdrop-filter</code> prefix for Safari. This tool always outputs both versions so your glass cards work correctly in all major browsers.
            </p>
            <div className="overflow-x-auto">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="bg-slate-50 dark:bg-slate-900/40">
                    <th className="text-left px-4 py-3 font-bold text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700 rounded-tl-lg">Browser</th>
                    <th className="text-left px-4 py-3 font-bold text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700">Support</th>
                    <th className="text-left px-4 py-3 font-bold text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700 rounded-tr-lg">Notes</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    ['Chrome 76+', '✅ Full', 'backdrop-filter supported natively'],
                    ['Firefox 103+', '✅ Full', 'Enabled by default since v103'],
                    ['Safari 9+', '✅ With prefix', '-webkit-backdrop-filter required'],
                    ['Edge 79+', '✅ Full', 'Based on Chromium, full support'],
                    ['IE 11', '❌ No support', 'backdrop-filter not supported — use fallback'],
                  ].map(([browser, support, note], i) => (
                    <tr key={browser} className={i % 2 === 0 ? 'bg-white dark:bg-slate-800' : 'bg-slate-50 dark:bg-slate-900/30'}>
                      <td className="px-4 py-2.5 font-semibold text-slate-900 dark:text-white border border-slate-200 dark:border-slate-700">{browser}</td>
                      <td className="px-4 py-2.5 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700">{support}</td>
                      <td className="px-4 py-2.5 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 text-xs">{note}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-8 shadow-sm">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">Frequently Asked Questions</h2>
            <div className="space-y-4">
              {[
                { q: 'Why does my glass card look solid and not transparent?', a: 'The backdrop-filter: blur() property only creates a visible effect when there is something behind the element — ideally a colourful gradient or image. If your page has a plain white or dark background, the blur has very little visible effect. Place the glass card over a vibrant gradient background to see the full frosted glass effect.' },
                { q: 'Why does the blur effect not work in Firefox?', a: 'Firefox enabled backdrop-filter by default from version 103. If you are using Firefox below 103, the effect will not appear. You can add a fallback: @supports not (backdrop-filter: blur()) { .glass-card { background: rgba(r, g, b, 0.85); } } to show a more opaque fallback for unsupported browsers.' },
                { q: 'What is the difference between opacity and glass opacity?', a: 'The opacity CSS property makes the entire element and all its children transparent. The glassmorphism technique uses background: rgba() instead, which only makes the element\'s background semi-transparent while keeping the content (text, icons) fully visible.' },
                { q: 'Can I use these glass cards on dark backgrounds?', a: 'Yes, but the effect looks different. On dark backgrounds, a white-tinted glass with low opacity shows a subtle frosted sheen. For dark backgrounds, try the midnight or cosmic presets and reduce the blur to 8–12px for a more defined look.' },
                { q: 'What output formats does this generator support?', a: 'Four formats: plain CSS (`.glass-card` class with all properties), SCSS (same but with variables for easy editing), Tailwind CSS (utility class HTML snippet), and React (inline style object as a functional component). All four are updated in real time as you adjust the controls.' },
                { q: 'What does the saturation control do?', a: 'The backdrop-filter: saturate() property boosts the colour vibrancy of whatever is visible behind the glass. At 100% there is no change. Values above 150% make the colours behind the glass more vivid and intense, which gives the frosted effect a higher-quality, glowing look. This is always applied together with blur() in the backdrop-filter property.' },
                { q: 'How do I add the glass effect to an existing element?', a: 'Copy the CSS from the generator and add the .glass-card class to your HTML element. Make sure the element is positioned over a colourful background (not a plain white page). Also ensure the element does not have overflow: hidden if you want the blur to extend beyond its bounds.' },
                { q: 'What is the -webkit-backdrop-filter prefix for?', a: 'This vendor prefix is required for Safari compatibility. Chrome, Firefox, and Edge support the standard backdrop-filter property, but Safari requires the -webkit- prefix. This generator always outputs both to ensure cross-browser support.' },
              ].map(({ q, a }) => (
                <details key={q} className="group border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden">
                  <summary className="flex items-center justify-between cursor-pointer px-5 py-4 font-semibold text-slate-900 dark:text-white hover:bg-slate-50 dark:hover:bg-slate-700/50 transition select-none text-sm">
                    <span>{q}</span><span className="text-slate-400 text-lg group-open:rotate-45 transition-transform flex-shrink-0 ml-4">+</span>
                  </summary>
                  <div className="px-5 pb-5 pt-3 text-slate-600 dark:text-slate-400 text-sm leading-relaxed border-t border-slate-100 dark:border-slate-700">{a}</div>
                </details>
              ))}
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}