// app/api/gitignore/route.js
import { NextResponse } from 'next/server';

// Special URL overrides for templates that live outside the root directory
const TEMPLATE_URL_MAP = {
  NextJS: 'https://raw.githubusercontent.com/github/gitignore/main/community/JavaScript/NextJS.gitignore',
  JetBrains: 'https://raw.githubusercontent.com/github/gitignore/main/Global/JetBrains.gitignore',
  macOS: 'https://raw.githubusercontent.com/github/gitignore/main/Global/macOS.gitignore',
  Windows: 'https://raw.githubusercontent.com/github/gitignore/main/Global/Windows.gitignore',
  Linux: 'https://raw.githubusercontent.com/github/gitignore/main/Global/Linux.gitignore',
  VisualStudioCode: 'https://raw.githubusercontent.com/github/gitignore/main/Global/VisualStudioCode.gitignore',
  Android: 'https://raw.githubusercontent.com/github/gitignore/main/Android.gitignore',
};

// React has no single dedicated file — we use a merged pattern from Node + CRA conventions
const REACT_CONTENT = `# Dependencies
node_modules/
/.pnp
.pnp.js

# Build output
/build
/dist
/.next/
/out/

# Testing
/coverage

# Env files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Editor
.DS_Store
.vscode/
.idea/

# Misc
*.pem
.vercel
`;

function getTemplateUrl(name) {
  if (TEMPLATE_URL_MAP[name]) return TEMPLATE_URL_MAP[name];
  return `https://raw.githubusercontent.com/github/gitignore/main/${name}.gitignore`;
}

function buildHeader(name) {
  return [
    '# =================================================',
    `# ${name.toUpperCase()}`,
    '# Generated by omniwebkit.com/tools/gitignore-generator',
    '# =================================================',
    '',
  ].join('\n');
}

function deduplicateLines(combined) {
  const lines = combined.split('\n');
  const seen = new Set();
  const result = [];

  for (const line of lines) {
    const trimmed = line.trim();

    // Always keep empty lines and comment lines (even duplicates)
    if (trimmed === '' || trimmed.startsWith('#')) {
      result.push(line);
      continue;
    }

    if (!seen.has(trimmed)) {
      seen.add(trimmed);
      result.push(line);
    }
    // else: skip duplicate non-comment, non-empty line
  }

  return result.join('\n');
}

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const raw = searchParams.get('templates');

  if (!raw || raw.trim() === '') {
    return new NextResponse('Please select at least one template', { status: 400 });
  }

  const templateNames = raw
    .split(',')
    .map((t) => t.trim())
    .filter(Boolean);

  if (templateNames.length === 0) {
    return new NextResponse('Please select at least one template', { status: 400 });
  }

  const sections = [];
  let anySuccess = false;
  let githubUnreachable = false;

  for (const name of templateNames) {
    // Special case: React is handled inline
    if (name === 'React') {
      sections.push(buildHeader('React') + REACT_CONTENT);
      anySuccess = true;
      continue;
    }

    const url = getTemplateUrl(name);

    try {
      const res = await fetch(url, {
        next: { revalidate: 86400 }, // cache 24h
      });

      if (res.status === 404) {
        sections.push(`# ${name} template unavailable\n`);
        continue;
      }

      if (!res.ok) {
        if (res.status >= 500) githubUnreachable = true;
        sections.push(`# ${name} template unavailable\n`);
        continue;
      }

      const content = await res.text();
      sections.push(buildHeader(name) + content);
      anySuccess = true;
    } catch {
      githubUnreachable = true;
      sections.push(`# ${name} template unavailable\n`);
    }
  }

  if (githubUnreachable && !anySuccess) {
    return new NextResponse('GitHub template service unavailable, try again', { status: 503 });
  }

  if (!anySuccess) {
    return new NextResponse('No valid templates found', { status: 404 });
  }

  const combined = sections.join('\n\n');
  const deduplicated = deduplicateLines(combined);

  return new NextResponse(deduplicated, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': 'attachment; filename=".gitignore"',
      'Cache-Control': 'public, max-age=86400',
    },
  });
}
