'use client';
import { useState, useMemo } from 'react';
import { Bot, Plus, X, Copy, Check, Download, FileText, Shield, ShieldOff, ShieldCheck } from 'lucide-react';
import Breadcrumbs from '@/components/seo/Breadcrumbs';

/* ─── Styles ────────────────────────────────────────────────────────── */
const cardCls = 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl shadow-sm';
const inputCls = 'w-full px-3 py-2 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl text-sm font-mono text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-violet-500/40 transition';
const labelCls = 'block text-[10px] font-black uppercase tracking-wide text-slate-400 mb-1';

const PRESETS = [
    { name: 'Allow All', icon: ShieldCheck, rules: [{ agent: '*', allow: ['/'], disallow: [] }], sitemaps: [] },
    { name: 'Block All', icon: ShieldOff, rules: [{ agent: '*', allow: [], disallow: ['/'] }], sitemaps: [] },
    { name: 'WordPress', icon: Shield, rules: [{ agent: '*', allow: ['/'], disallow: ['/wp-admin/', '/wp-includes/', '/wp-content/plugins/', '/trackback/', '/feed/', '/?s=', '/search/'] }], sitemaps: ['/sitemap.xml'] },
    { name: 'Next.js', icon: Shield, rules: [{ agent: '*', allow: ['/'], disallow: ['/_next/', '/api/', '/404', '/500'] }], sitemaps: ['/sitemap.xml'] },
    { name: 'E-commerce', icon: Shield, rules: [{ agent: '*', allow: ['/'], disallow: ['/cart/', '/checkout/', '/account/', '/admin/', '/search?', '/wishlist/', '/*?sort=', '/*?filter='] }], sitemaps: ['/sitemap.xml'] },
];

export default function RobotsTxtGenerator() {
    const [rules, setRules] = useState([{ agent: '*', allow: ['/'], disallow: [] }]);
    const [sitemaps, setSitemaps] = useState(['']);
    const [crawlDelay, setCrawlDelay] = useState('');
    const [host, setHost] = useState('');
    const [copied, setCopied] = useState(false);

    const addRule = () => setRules([...rules, { agent: '', allow: [], disallow: [''] }]);
    const rmRule = (i) => setRules(rules.filter((_, j) => j !== i));
    const upAgent = (i, v) => { const r = [...rules]; r[i].agent = v; setRules(r); };
    const addAllow = (i) => { const r = [...rules]; r[i].allow.push(''); setRules(r); };
    const addDisallow = (i) => { const r = [...rules]; r[i].disallow.push(''); setRules(r); };
    const upAllow = (ri, ai, v) => { const r = [...rules]; r[ri].allow[ai] = v; setRules(r); };
    const upDisallow = (ri, di, v) => { const r = [...rules]; r[ri].disallow[di] = v; setRules(r); };
    const rmAllow = (ri, ai) => { const r = [...rules]; r[ri].allow.splice(ai, 1); setRules(r); };
    const rmDisallow = (ri, di) => { const r = [...rules]; r[ri].disallow.splice(di, 1); setRules(r); };
    const addSitemap = () => setSitemaps([...sitemaps, '']);
    const upSitemap = (i, v) => { const s = [...sitemaps]; s[i] = v; setSitemaps(s); };
    const rmSitemap = (i) => setSitemaps(sitemaps.filter((_, j) => j !== i));
    const applyPreset = (p) => { setRules(JSON.parse(JSON.stringify(p.rules))); setSitemaps([...p.sitemaps]); };

    const output = useMemo(() => {
        const L = ['# robots.txt generated by OmniWebKit', `# Generated: ${new Date().toISOString().split('T')[0]}`, ''];
        rules.forEach(rule => {
            if (!rule.agent) return;
            L.push(`User-agent: ${rule.agent}`);
            if (crawlDelay && rule.agent === '*') L.push(`Crawl-delay: ${crawlDelay}`);
            rule.disallow.filter(Boolean).forEach(d => L.push(`Disallow: ${d}`));
            rule.allow.filter(Boolean).forEach(a => L.push(`Allow: ${a}`));
            L.push('');
        });
        if (host) L.push(`Host: ${host}`, '');
        sitemaps.filter(Boolean).forEach(s => L.push(`Sitemap: ${s}`));
        return L.join('\n');
    }, [rules, sitemaps, crawlDelay, host]);

    const lineCount = output.split('\n').length;
    const copyOut = () => { navigator.clipboard.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 1500); };
    const dlFile = () => { const b = new Blob([output], { type: 'text/plain' }); Object.assign(document.createElement('a'), { href: URL.createObjectURL(b), download: 'robots.txt' }).click(); };

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-900 py-8 px-4">
            <div className="max-w-5xl mx-auto">
        <Breadcrumbs items={[{ name: 'robots.txt Generator', href: '/tools/robots-txt-generator' }]} />

                {/* Header */}
                <div className="text-center mb-8">
                    <div className="inline-flex items-center justify-center w-14 h-14 bg-gradient-to-br from-violet-500 to-purple-600 rounded-2xl mb-4 shadow-lg shadow-violet-500/25">
                        <Bot className="w-7 h-7 text-white" />
                    </div>
                    <h1 className="text-4xl sm:text-5xl font-bold text-slate-900 dark:text-white mb-2">robots.txt Generator</h1>
                    <p className="text-slate-600 dark:text-slate-400 text-lg">Build a robots.txt file for your website — presets, rules, sitemaps</p>
                </div>

                <div className="grid lg:grid-cols-2 gap-5">

                    {/* Editor */}
                    <div className="space-y-4">

                        {/* Presets */}
                        <div className={`${cardCls} p-4`}>
                            <h3 className="text-xs font-black text-slate-900 dark:text-white uppercase tracking-wide mb-3">Quick Presets</h3>
                            <div className="flex flex-wrap gap-2">
                                {PRESETS.map((p, i) => (
                                    <button key={i} onClick={() => applyPreset(p)}
                                        className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold bg-violet-50 dark:bg-violet-900/20 text-violet-600 dark:text-violet-400 border border-violet-200 dark:border-violet-800 rounded-xl hover:bg-violet-100 dark:hover:bg-violet-900/40 transition">
                                        <p.icon className="w-3 h-3" />{p.name}
                                    </button>
                                ))}
                            </div>
                        </div>

                        {/* Rules */}
                        {rules.map((rule, ri) => (
                            <div key={ri} className={`${cardCls} p-4`}>
                                <div className="flex items-center justify-between mb-3">
                                    <h3 className="text-xs font-black text-slate-900 dark:text-white uppercase tracking-wide">Rule #{ri + 1}</h3>
                                    {rules.length > 1 && <button onClick={() => rmRule(ri)} className="text-slate-400 hover:text-red-500 transition"><X className="w-4 h-4" /></button>}
                                </div>

                                <label className={labelCls}>User-agent</label>
                                <input value={rule.agent} onChange={e => upAgent(ri, e.target.value)} placeholder="*" className={`${inputCls} mb-3`} />

                                {/* Disallow */}
                                <div className="mb-3">
                                    <div className="flex items-center justify-between mb-1">
                                        <label className={labelCls}>Disallow</label>
                                        <button onClick={() => addDisallow(ri)} className="text-[10px] font-bold text-red-500 hover:text-red-600 flex items-center gap-0.5 transition"><Plus className="w-3 h-3" />Add</button>
                                    </div>
                                    {rule.disallow.map((d, di) => (
                                        <div key={di} className="flex gap-2 mb-1">
                                            <input value={d} onChange={e => upDisallow(ri, di, e.target.value)} placeholder="/path/"
                                                className="flex-1 px-3 py-1.5 bg-red-50 dark:bg-red-900/10 border border-red-200 dark:border-red-800 rounded-xl text-xs font-mono text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-red-500/40" />
                                            <button onClick={() => rmDisallow(ri, di)} className="text-slate-400 hover:text-red-500 transition"><X className="w-3.5 h-3.5" /></button>
                                        </div>
                                    ))}
                                </div>

                                {/* Allow */}
                                <div>
                                    <div className="flex items-center justify-between mb-1">
                                        <label className={labelCls}>Allow</label>
                                        <button onClick={() => addAllow(ri)} className="text-[10px] font-bold text-emerald-500 hover:text-emerald-600 flex items-center gap-0.5 transition"><Plus className="w-3 h-3" />Add</button>
                                    </div>
                                    {rule.allow.map((a, ai) => (
                                        <div key={ai} className="flex gap-2 mb-1">
                                            <input value={a} onChange={e => upAllow(ri, ai, e.target.value)} placeholder="/path/"
                                                className="flex-1 px-3 py-1.5 bg-emerald-50 dark:bg-emerald-900/10 border border-emerald-200 dark:border-emerald-800 rounded-xl text-xs font-mono text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-emerald-500/40" />
                                            <button onClick={() => rmAllow(ri, ai)} className="text-slate-400 hover:text-red-500 transition"><X className="w-3.5 h-3.5" /></button>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}

                        <button onClick={addRule}
                            className="w-full py-2.5 border-2 border-dashed border-slate-300 dark:border-slate-600 rounded-xl text-sm text-slate-500 dark:text-slate-400 hover:border-violet-400 hover:text-violet-500 dark:hover:border-violet-500 dark:hover:text-violet-400 transition flex items-center justify-center gap-2">
                            <Plus className="w-4 h-4" />Add Rule
                        </button>

                        {/* Extra settings */}
                        <div className={`${cardCls} p-4`}>
                            <h3 className="text-xs font-black text-slate-900 dark:text-white uppercase tracking-wide mb-3">Additional Settings</h3>
                            <div className="grid grid-cols-2 gap-3 mb-3">
                                <div><label className={labelCls}>Crawl-delay (sec)</label><input value={crawlDelay} onChange={e => setCrawlDelay(e.target.value)} placeholder="10" type="number" className={inputCls} /></div>
                                <div><label className={labelCls}>Host</label><input value={host} onChange={e => setHost(e.target.value)} placeholder="https://example.com" className={inputCls} /></div>
                            </div>
                            <div className="flex items-center justify-between mb-1">
                                <label className={labelCls}>Sitemaps</label>
                                <button onClick={addSitemap} className="text-[10px] font-bold text-violet-500 hover:text-violet-600 flex items-center gap-0.5 transition"><Plus className="w-3 h-3" />Add</button>
                            </div>
                            {sitemaps.map((s, i) => (
                                <div key={i} className="flex gap-2 mb-1">
                                    <input value={s} onChange={e => upSitemap(i, e.target.value)} placeholder="https://example.com/sitemap.xml" className={`${inputCls} flex-1`} />
                                    <button onClick={() => rmSitemap(i)} className="text-slate-400 hover:text-red-500 transition"><X className="w-3.5 h-3.5" /></button>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Output */}
                    <div className={`${cardCls} p-5 h-fit lg:sticky lg:top-8`}>
                        <div className="flex items-center justify-between mb-4">
                            <h3 className="text-xs font-black text-slate-900 dark:text-white uppercase tracking-wide flex items-center gap-1.5"><FileText className="w-3.5 h-3.5 text-violet-500" />robots.txt Output</h3>
                            <div className="flex gap-2">
                                <button onClick={copyOut}
                                    className="flex items-center gap-1 px-3 py-1.5 text-[10px] font-bold bg-slate-100 dark:bg-slate-700 rounded-lg text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-600 transition">
                                    {copied ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3" />}{copied ? 'Copied' : 'Copy'}
                                </button>
                                <button onClick={dlFile}
                                    className="flex items-center gap-1 px-3 py-1.5 text-[10px] font-bold bg-gradient-to-r from-violet-500 to-purple-600 text-white rounded-lg hover:from-violet-600 hover:to-purple-700 shadow-sm transition">
                                    <Download className="w-3 h-3" />Download
                                </button>
                            </div>
                        </div>
                        <div className="flex items-center gap-2 mb-2">
                            <span className="text-[10px] font-bold text-slate-400">{lineCount} lines</span>
                            <span className="text-[10px] text-slate-300 dark:text-slate-600">•</span>
                            <span className="text-[10px] font-bold text-slate-400">{output.length} chars</span>
                        </div>
                        <div className="bg-slate-950 rounded-xl p-4 min-h-[300px] overflow-auto">
                            <pre className="text-xs text-emerald-400 font-mono whitespace-pre-wrap">{output}</pre>
                        </div>
                    </div>
                </div>

                {/* ── SEO Content ── */}
                <div className="mt-10 space-y-5">

                    <div className={`${cardCls} p-8`}>
                        <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Free Online robots.txt Generator — Build Your File in Seconds</h2>
                        <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
                            Every website needs a robots.txt file. It tells search engine crawlers which pages they can access and which ones they should skip. Without it, crawlers may index pages you want to keep private — admin panels, checkout flows, search result pages, or duplicate content. A properly configured robots.txt file improves your SEO, reduces server load, and keeps your site clean in search results.
                        </p>
                        <p className="text-slate-700 dark:text-slate-300 leading-relaxed mb-4">
                            This free robots.txt Generator lets you build the file visually. Add rules for different user agents, specify Allow and Disallow paths, set a crawl delay, add your sitemap URLs, and see the output in real time. Five presets are included: Allow All, Block All, WordPress, Next.js, and E-commerce. Each preset is a one-click starting point that you can customise.
                        </p>
                        <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                            When you are finished, copy the output to your clipboard or download it as a robots.txt file. Upload it to the root directory of your website. All processing runs in your browser — no data is sent to any server.
                        </p>
                    </div>

                    <div className={`${cardCls} p-8`}>
                        <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-5">Understanding robots.txt Directives</h2>
                        <div className="grid sm:grid-cols-2 gap-4">
                            {[
                                { t: 'User-agent', c: 'text-violet-600 dark:text-violet-400', b: 'Specifies which crawler the rules apply to. Use * for all crawlers, or name a specific bot like Googlebot, Bingbot, or Yandex.' },
                                { t: 'Disallow', c: 'text-red-600 dark:text-red-400', b: 'Tells the crawler NOT to access a specific path. Disallow: /admin/ blocks the entire /admin/ directory. Disallow: / blocks the entire site.' },
                                { t: 'Allow', c: 'text-emerald-600 dark:text-emerald-400', b: 'Overrides a Disallow rule for a specific path. Useful when you block a directory but want to allow a specific file within it.' },
                                { t: 'Sitemap', c: 'text-blue-600 dark:text-blue-400', b: 'Points crawlers to your XML sitemap. This helps search engines discover all your pages. Use the full URL: https://example.com/sitemap.xml.' },
                                { t: 'Crawl-delay', c: 'text-amber-600 dark:text-amber-400', b: 'Requests that crawlers wait a number of seconds between requests. Not all crawlers honour this directive, but it can reduce server load.' },
                                { t: 'Host', c: 'text-teal-600 dark:text-teal-400', b: 'Specifies the preferred domain for your site. Primarily used by Yandex. Most sites do not need this directive.' },
                            ].map(({ t, c, b }) => (
                                <div key={t} className="p-4 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700 rounded-xl">
                                    <h3 className={`font-black text-sm mb-1.5 ${c}`}>{t}</h3>
                                    <p className="text-slate-500 dark:text-slate-400 text-xs leading-relaxed">{b}</p>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className={`${cardCls} p-8`}>
                        <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-5">Five Presets Explained</h2>
                        <div className="space-y-3">
                            {[
                                { t: 'Allow All', c: 'text-emerald-600 dark:text-emerald-400', b: 'Allows all crawlers to access all pages. This is the most open configuration. Use it if you have nothing to hide and want maximum indexing.' },
                                { t: 'Block All', c: 'text-red-600 dark:text-red-400', b: 'Blocks all crawlers from accessing any page. Use this for staging sites, development servers, or sites not ready for public indexing.' },
                                { t: 'WordPress', c: 'text-blue-600 dark:text-blue-400', b: 'Blocks common WordPress admin directories, plugin files, trackbacks, feeds, and internal search results. Includes a sitemap directive.' },
                                { t: 'Next.js', c: 'text-violet-600 dark:text-violet-400', b: 'Blocks Next.js internal routes (_next), API routes, and error pages (404, 500). Includes a sitemap directive.' },
                                { t: 'E-commerce', c: 'text-amber-600 dark:text-amber-400', b: 'Blocks cart, checkout, account, admin, search queries, wishlist, and URL parameters for sorting and filtering. Keeps product pages indexed.' },
                            ].map(({ t, c, b }) => (
                                <div key={t} className="flex items-start gap-3 p-4 bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-700 rounded-xl">
                                    <div className={`w-2 h-2 rounded-full mt-2 flex-shrink-0 ${c.replace('text-', 'bg-').split(' ')[0]}`} />
                                    <div>
                                        <p className={`font-black text-sm mb-0.5 ${c}`}>{t}</p>
                                        <p className="text-slate-500 dark:text-slate-400 text-xs leading-relaxed">{b}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className={`${cardCls} p-8`}>
                        <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">Frequently Asked Questions</h2>
                        <div className="space-y-4">
                            {[
                                { q: 'Is this robots.txt generator free?', a: 'Yes, completely free with no account, no limits, and no data collection.' },
                                { q: 'Where do I put the robots.txt file?', a: 'Upload it to the root directory of your website: https://yourdomain.com/robots.txt. Most web hosts let you upload via FTP or your hosting panel.' },
                                { q: 'Does robots.txt block pages from Google?', a: 'Robots.txt tells crawlers not to crawl certain pages, but it does not prevent indexing. To block indexing, use a noindex meta tag instead.' },
                                { q: 'What is the crawl-delay directive?', a: 'It requests that crawlers wait a number of seconds between requests. Google ignores this directive, but Bing and Yandex honour it.' },
                                { q: 'Can I have multiple User-agent blocks?', a: 'Yes. You can create separate rules for different crawlers. For example, one block for Googlebot and another for Bingbot.' },
                                { q: 'What is the Sitemap directive?', a: 'It points crawlers to your XML sitemap, helping them discover all your pages. Use the full URL.' },
                                { q: 'Do I need a robots.txt file?', a: 'Technically no, but it is strongly recommended. Without one, crawlers will access everything, which may include pages you do not want indexed.' },
                                { q: 'Does this tool send my data to a server?', a: 'No. Everything runs in your browser. Your configuration is never uploaded anywhere.' },
                            ].map(({ q, a }) => (
                                <details key={q} className="group border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden">
                                    <summary className="flex items-center justify-between cursor-pointer px-5 py-4 font-semibold text-slate-900 dark:text-white hover:bg-slate-50 dark:hover:bg-slate-700/50 transition select-none text-sm">
                                        <span>{q}</span>
                                        <span className="text-slate-400 text-lg group-open:rotate-45 transition-transform flex-shrink-0 ml-4">+</span>
                                    </summary>
                                    <div className="px-5 pb-5 pt-3 text-slate-600 dark:text-slate-400 text-sm leading-relaxed border-t border-slate-100 dark:border-slate-700">{a}</div>
                                </details>
                            ))}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
}
